version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
    # Disable version updates, this does not affect security updates
    open-pull-requests-limit: 0
