packages:
  - 'packages/*'
catalog:
  '@angular/cli': '21.0.2'
  '@angular/compiler': '21.0.3'
  '@commitlint/cli': '20.1.0'
  '@commitlint/config-conventional': '20.0.0'
  '@eslint/core': '1.0.0'
  '@mdn/browser-compat-data': '7.1.24'
  '@nx/devkit': '22.1.3'
  '@nx/esbuild': '22.1.3'
  '@nx/eslint': '22.1.3'
  '@nx/eslint-plugin': '22.1.3'
  '@nx/js': '22.1.3'
  '@nx/plugin': '22.1.3'
  '@nx/vite': '22.1.3'
  '@nx/workspace': '22.1.3'
  '@schematics/angular': '21.0.2'
  '@swc-node/register': '1.11.1'
  '@swc/cli': '0.7.9'
  '@swc/core': '1.15.3'
  '@swc/helpers': '0.5.17'
  '@types/aria-query': '5.0.4'
  '@types/eslint-scope': '8.3.2'
  '@types/node': '22.19.1'
  '@types/semver': '^7.5.8'
  '@types/yargs': '^17.0.33'
  '@vitest/coverage-v8': '^4.0.3'
  cz-conventional-changelog: '3.3.0'
  esbuild: '^0.27.0'
  eslint: '9.39.1'
  eslint-config-prettier: '10.1.5'
  execa: '5.1.1'
  husky: '9.1.7'
  json-schema-to-typescript: '15.0.4'
  json-schema-traverse: '1.0.0'
  jsonc-eslint-parser: '2.4.1'
  lint-staged: '16.2.7'
  ncp: '2.0.0'
  nx: '22.1.3'
  picocolors: '1.1.1'
  pkg-pr-new: '0.0.62'
  prettier: '3.7.3'
  tree-kill: '1.2.2'
  ts-node: '10.9.2'
  tslib: '^2.4.1'
  tsx: '4.21.0'
  typescript: '5.9.3'
  verdaccio: '6.2.4'
  vite: '^7.1.12'
  vitest: '^4.0.3'
  yargs: '18.0.0'
catalogMode: 'prefer'
catalogs:
  other-runtime-dependencies:
    '@angular/cli': '>= 21.0.0 < 22.0.0'
    '@angular-devkit/architect': '>= 0.2100.0 < 0.2200.0'
    '@angular-devkit/core': '>= 21.0.0 < 22.0.0'
    '@angular-devkit/schematics': '>= 21.0.0 < 22.0.0'
    aria-query: '5.3.2'
    axobject-query: '4.1.0'
    eslint-scope: '^9.0.0'
    ignore: '7.0.5'
    semver: '7.7.3'
    strip-json-comments: '3.1.1'
    ts-api-utils: '^2.1.0'
  typescript-eslint:
    '@typescript-eslint/rule-tester': '8.48.1'
    '@typescript-eslint/types': '8.48.1'
    '@typescript-eslint/utils': '8.48.1'
    typescript-eslint: '8.48.1'
cleanupUnusedCatalogs: true
ignoredBuiltDependencies:
  - 'core-js'
onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'
  - 'nx'
