packages:
  - packages/*

catalog:
  '@angular/cli': 20.3.8
  '@angular/compiler': 20.3.9
  '@commitlint/cli': 20.1.0
  '@commitlint/config-conventional': 20.0.0
  '@jest/types': 30.0.5
  '@mdn/browser-compat-data': 7.1.18
  '@nx/devkit': 22.1.0-beta.3
  '@nx/esbuild': 22.1.0-beta.3
  '@nx/eslint': 22.1.0-beta.3
  '@nx/eslint-plugin': 22.1.0-beta.3
  '@nx/jest': 22.1.0-beta.3
  '@nx/js': 22.1.0-beta.3
  '@nx/plugin': 22.1.0-beta.3
  '@nx/vite': 22.1.0-beta.3
  '@nx/workspace': 22.1.0-beta.3
  '@schematics/angular': 20.3.8
  '@swc-node/register': 1.11.1
  '@swc/cli': 0.7.8
  '@swc/core': 1.14.0
  '@swc/helpers': 0.5.17
  '@types/aria-query': 5.0.4
  '@types/eslint-scope': 8.3.2
  '@types/jest': 30.0.0
  '@types/node': 22.18.13
  '@types/semver': ^7.5.8
  '@types/yargs': ^17.0.33
  '@vitest/coverage-v8': ^4.0.3
  cz-conventional-changelog: 3.3.0
  esbuild: ^0.25.10
  eslint: 9.39.0
  eslint-config-prettier: 10.1.5
  execa: 5.1.1
  husky: 9.1.7
  jest: 30.0.5
  jest-util: 30.0.5
  json-schema-to-typescript: 15.0.4
  json-schema-traverse: 1.0.0
  jsonc-eslint-parser: 2.4.1
  lint-staged: 16.2.6
  ncp: 2.0.0
  nx: 22.1.0-beta.3
  picocolors: 1.1.1
  pkg-pr-new: 0.0.60
  prettier: 3.6.2
  prettier-v2-for-jest-inline-snapshots: npm:prettier@^2
  tree-kill: 1.2.2
  ts-jest: 29.4.1
  ts-node: 10.9.2
  tslib: ^2.4.1
  tsx: 4.20.6
  typescript: 5.9.3
  verdaccio: 6.2.1
  vite: ^7.1.12
  vitest: ^4.0.3
  yargs: 18.0.0

catalogMode: prefer

catalogs:
  other-runtime-dependencies:
    '@angular-devkit/architect': '>= 0.2000.0 < 0.2100.0'
    '@angular-devkit/core': '>= 20.0.0 < 21.0.0'
    '@angular-devkit/schematics': '>= 20.0.0 < 21.0.0'
    aria-query: 5.3.2
    axobject-query: 4.1.0
    eslint-scope: ^8.0.2
    ignore: 7.0.5
    semver: 7.7.3
    strip-json-comments: 3.1.1
    ts-api-utils: ^2.1.0
  typescript-eslint:
    '@typescript-eslint/rule-tester': 8.46.3
    '@typescript-eslint/types': 8.46.3
    '@typescript-eslint/utils': 8.46.3
    typescript-eslint: 8.46.3

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
