name: 'Check Package Changes'
description: 'Checks if specified packages were changed in pnpm-workspace.yaml between HEAD and HEAD~1'

inputs:
  packages:
    description: |
      Newline-separated list of packages to check. Each line should be in the format:
      package-name:catalog-path

      Examples:
        eslint:.catalog["eslint"]
        @nx/workspace:.catalog["@nx/workspace"]
        @typescript-eslint/rule-tester:.catalogs.typescript-eslint["@typescript-eslint/rule-tester"]
    required: true

outputs:
  was-changed:
    description: 'Whether any of the specified packages were changed (true/false)'
    value: ${{ steps.check.outputs.was-changed }}

runs:
  using: 'composite'
  steps:
    - name: Check for package changes
      id: check
      shell: bash
      env:
        PACKAGES_INPUT: ${{ inputs.packages }}
      run: |
        changed=false

        # Debug: show yq version
        echo "Using yq version: $(yq --version)"

        # Debug: show input
        echo "Packages to check:"
        echo "$PACKAGES_INPUT"
        echo "---"

        # Process each line
        while IFS= read -r entry || [ -n "$entry" ]; do
          # Skip empty lines
          [ -z "$entry" ] && continue

          # Split on first colon only
          package="${entry%%:*}"
          yq_path="${entry#*:}"

          echo "Checking $package at path $yq_path"

          # Extract version from current commit
          CURRENT_VERSION=$(yq eval "$yq_path // \"\"" pnpm-workspace.yaml 2>&1) || {
            echo "Warning: Failed to get current version for $package"
            CURRENT_VERSION=""
          }

          # Extract version from previous commit
          PREVIOUS_VERSION=$(git show HEAD~1:pnpm-workspace.yaml 2>/dev/null | yq eval "$yq_path // \"\"" 2>&1) || {
            echo "Warning: Failed to get previous version for $package"
            PREVIOUS_VERSION=""
          }

          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "✓ $package changed from '$PREVIOUS_VERSION' to '$CURRENT_VERSION'"
            changed=true
          else
            echo "✗ $package unchanged ('$CURRENT_VERSION')"
          fi
        done <<< "$PACKAGES_INPUT"

        if [ "$changed" = true ]; then
          echo "was-changed=true" >> "$GITHUB_OUTPUT"
        fi
