name: Publish PR branch to pkg.pr.new

on:
  pull_request_review_comment:
    types: [created]

# Minimal permissions by default
permissions:
  contents: read

env:
  NX_NO_CLOUD: true

jobs:
  publish_pr_branch_to_pkg_pr_new:
    name: Publish PR branch to pkg.pr.new
    if: github.actor == 'JamesHenry'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js per package.json
        uses: actions/setup-node@v5
        with:
          # Use the volta.node property as the source of truth
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: Build packages
        run: pnpm build

      - name: Publish PR branch to pkg.pr.new
        run: pnpm exec pkg-pr-new publish --pnpm --compact --peerDeps --no-template './packages/*'
