# WARNING: This workflow can be run on forks, so it is important to not perform any sensitive operations
# or expose any secrets.
#
# pkg.pr.new as a registry is not the source of truth for the packages, npm is, so even if somehow a 
# malicious actor were able to leverage this workflow to publish malware, nobody would receive it
# automatically, they would have to install a super specific URL.

name: Publish PR branch to pkg.pr.new

on:
  pull_request_review:
    types: [submitted]

# Minimal permissions by default
permissions:
  contents: read

env:
  # Intentionally no access to Nx Cloud
  NX_NO_CLOUD: true
  NX_CLOUD_ACCESS_TOKEN: ""

jobs:
  publish_pr_branch_to_pkg_pr_new:
    name: Publish PR branch to pkg.pr.new
    if: github.actor == 'JamesHenry' && github.event.review.state == 'commented' && github.event.review.body == '@pkg-pr-new publish'
    runs-on: ubuntu-latest
    steps:
      # Check out the PR branch HEAD
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js per package.json
        uses: actions/setup-node@v5
        with:
          # Use the volta.node property as the source of truth
          node-version-file: 'package.json'
          # Disable caching given this workflow could be run on forks (security risk)
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: Build packages
        run: pnpm build

      - name: Publish PR branch to pkg.pr.new
        run: pnpm exec pkg-pr-new publish --pnpm --compact --peerDeps --no-template './packages/*'
