/**
 * DO NOT EDIT THIS FILE
 *
 * In order to update this config, please run `yarn update-rule-configs`.
 */

import type { TSESLint } from '@typescript-eslint/utils';

import templateBaseConfig from './template-base';

export default (
  plugin: TSESLint.FlatConfig.Plugin,
  parser: TSESLint.FlatConfig.Parser,
): TSESLint.FlatConfig.ConfigArray => [
  templateBaseConfig(plugin, parser),
  {
    name: 'angular-eslint/template-recommended',
    rules: {
      '@angular-eslint/template/banana-in-box': 'error',
      '@angular-eslint/template/eqeqeq': 'error',
      '@angular-eslint/template/no-negated-async': 'error',
    },
  },
];
